[build]
target = "riscv32imc-unknown-none-elf"

[target."riscv32imc-unknown-none-elf"]
runner = "wchisp --usb flash" # flash over USB bootloader
# runner = "wlink flash --enable-sdi-print --watch-serial" # flash over debug pins
